name: example
services:
  webserver:
    build: ./webserver
    networks:
      lan:
        ipv4_address: 10.5.0.3
  attacker:
    build: ./attacker
    networks:
      lan:
        ipv4_address: 10.5.0.2
        
networks:
  lan:
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1